# Generated by Django 2.2.4 on 2022-05-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20220519_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2022-05-26', max_length=20, verbose_name='出生日期'),
        ),
    ]
